# Household Electricity Consumption Prediction

## Data Understanding

This notebook is used to understand and inspect the household electricity consumption dataset.

### Project Objective

The objective of this project is to predict monthly household electricity consumption using machine learning.

In [11]:
import pandas as pd

In [13]:
df=pd.read_csv("household_power_consumption.csv")

In [14]:
df.head(10)

,Month,Province,District,Household_Type,Household_Size,House_Area_m2,Bedrooms,AC_Units,Fans,Refrigerators,...,Other_High_Power_Appliances,Avg_Daily_AC_Hours,Avg_Daily_Fan_Hours,Avg_Daily_TV_Hours,Avg_Daily_Cooking_Hours,Solar_PV,Solar_Capacity_kW,Avg_Temperature_C,Previous_Month_kWh,Target_Monthly_kWh
0,January,Eastern,Ampara,Single_Family,4,69.1,1,1.0,4,1,...,3,5.1,4.7,3.5,3.3,No,0.0,30.3,369.7,350.8
1,January,Eastern,Ampara,Apartment,6,54.1,2,0.0,7,1,...,0,0.0,NaN,6.3,3.0,No,0.0,30.3,290.9,281.8
2,January,North Central,Anuradhapura,Single_Family,2,196.9,5,0.0,3,1,...,1,0.0,10.7,4.1,3.9,No,NaN,25.4,241.6,277.9
3,January,North Central,Anuradhapura,Single_Family,4,122.8,3,0.0,4,2,...,3,0.0,9.2,5.7,3.7,No,0.0,27.4,270.7,286.7
4,January,Uva,Badulla,Single_Family,5,93.9,2,0.0,5,1,...,2,0.0,4.7,2.7,1.4,No,0.0,29.6,307.3,303.0
5,January,Eastern,Batticaloa,Single_Family,7,119.8,3,0.0,8,1,...,1,0.0,11.4,4.8,3.5,Yes,6.5,26.9,290.0,284.7
6,January,Eastern,Batticaloa,Single_Family,4,177.0,3,1.0,5,1,...,0,4.4,9.2,2.3,2.6,No,0.0,27.7,411.5,344.7
7,January,Western,Gampaha,Single_Family,7,NaN,4,1.0,7,1,...,3,2.1,6.5,3.3,1.3,No,0.0,30.8,438.1,492.7
8,January,Western,Gampaha,Single_Family,4,116.0,3,0.0,4,2,...,2,0.0,5.4,3.2,2.6,No,0.0,27.7,315.0,312.1
9,January,Southern,Hambantota,Single_Family,7,93.8,2,0.0,8,1,...,3,0.0,10.9,5.8,3.4,No,0.0,26.1,363.5,404.3

In [15]:
df.shape

(1000, 24)

In [16]:
df.columns

Index(['Month', 'Province', 'District', 'Household_Type', 'Household_Size',
       'House_Area_m2', 'Bedrooms', 'AC_Units', 'Fans', 'Refrigerators', 'TVs',
       'Washing_Machines', 'Water_Heaters', 'Computers',
       'Other_High_Power_Appliances', 'Avg_Daily_AC_Hours',
       'Avg_Daily_Fan_Hours', 'Avg_Daily_TV_Hours', 'Avg_Daily_Cooking_Hours',
       'Solar_PV', 'Solar_Capacity_kW', 'Avg_Temperature_C',
       'Previous_Month_kWh', 'Target_Monthly_kWh'],
      dtype='str')

In [17]:
df.info

<bound method DataFrame.info of         Month       Province      District Household_Type  Household_Size  \
0     January        Eastern        Ampara  Single_Family               4
1     January        Eastern        Ampara      Apartment               6
2     January  North Central  Anuradhapura  Single_Family               2
3     January  North Central  Anuradhapura  Single_Family               4
4     January            Uva       Badulla  Single_Family               5
..        ...            ...           ...            ...             ...
995  December   Sabaragamuwa     Ratnapura      Apartment               4
996  December   Sabaragamuwa     Ratnapura  Semi_Detached               5
997  December        Eastern   Trincomalee  Semi_Detached               3
998  December       Northern      Vavuniya      Apartment               7
999  December       Northern      Vavuniya  Semi_Detached               3

     House_Area_m2  Bedrooms  AC_Units  Fans  Refrigerators  ...  \
0             69.1         1       1.0     4              1  ...
1             54.1         2       0.0     7              1  ...
2            196.9         5       0.0     3              1  ...
3            122.8         3       0.0     4              2  ...
4             93.9         2       0.0     5              1  ...
..             ...       ...       ...   ...            ...  ...
995          101.3         1       0.0     4              1  ...
996          118.4         2       1.0     5              1  ...
997          136.2         3       1.0     4              1  ...
998          125.9         3       0.0     7              2  ...
999           87.3         2       1.0     4              2  ...

     Other_High_Power_Appliances  Avg_Daily_AC_Hours  Avg_Daily_Fan_Hours  \
0                              3                 5.1                  4.7
1                              0                 0.0                  NaN
2                              1                 0.0                 10.7
3                              3                 0.0                  9.2
4                              2                 0.0                  4.7
..                           ...                 ...                  ...
995                            1                 0.0                  7.9
996                            1                 4.7                  8.1
997                            0                 6.0                  8.7
998                            3                 NaN                  5.9
999                            2                 7.7                  6.3

     Avg_Daily_TV_Hours  Avg_Daily_Cooking_Hours  Solar_PV  Solar_Capacity_kW  \
0                   3.5                      3.3        No                0.0
1                   6.3                      3.0        No                0.0
2                   4.1                      3.9        No                NaN
3                   5.7                      3.7        No                0.0
4                   2.7                      1.4        No                0.0
..                  ...                      ...       ...                ...
995                 6.9                      3.4        No                0.0
996                 5.7                      1.7        No                0.0
997                 6.6                      3.9        No                0.0
998                 4.7                      1.9        No                0.0
999                 6.1                      3.3        No                0.0

     Avg_Temperature_C  Previous_Month_kWh Target_Monthly_kWh
0                 30.3               369.7              350.8
1                 30.3               290.9              281.8
2                 25.4               241.6              277.9
3                 27.4               270.7              286.7
4                 29.6               307.3              303.0
..                 ...                 ...                ...
995               25.9                 NaN              253.8
996               25.7               355.3              370.8
997               27.1               431.9              398.9
998               28.8               359.2              448.4
999               26.2               399.2              406.0

[1000 rows x 24 columns]>

In [18]:
df.dtypes

Month                              str
Province                           str
District                           str
Household_Type                     str
Household_Size                   int64
House_Area_m2                  float64
Bedrooms                         int64
AC_Units                       float64
Fans                             int64
Refrigerators                    int64
TVs                              int64
Washing_Machines                 int64
Water_Heaters                    int64
Computers                        int64
Other_High_Power_Appliances      int64
Avg_Daily_AC_Hours             float64
Avg_Daily_Fan_Hours            float64
Avg_Daily_TV_Hours             float64
Avg_Daily_Cooking_Hours        float64
Solar_PV                           str
Solar_Capacity_kW              float64
Avg_Temperature_C              float64
Previous_Month_kWh             float64
Target_Monthly_kWh             float64
dtype: object

In [19]:
df.describe()

,Household_Size,House_Area_m2,Bedrooms,AC_Units,Fans,Refrigerators,TVs,Washing_Machines,Water_Heaters,Computers,Other_High_Power_Appliances,Avg_Daily_AC_Hours,Avg_Daily_Fan_Hours,Avg_Daily_TV_Hours,Avg_Daily_Cooking_Hours,Solar_Capacity_kW,Avg_Temperature_C,Previous_Month_kWh,Target_Monthly_kWh
count,1000.000000,970.000000,1000.000000,980.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,960.000000,970.000000,1000.000000,1000.000000,980.000000,970.000000,950.000000,1000.000000
mean,3.981000,111.990103,2.523000,0.622449,4.969000,1.238000,1.953000,1.044000,0.837000,1.506000,1.513000,2.582188,7.982165,4.459100,2.514200,1.237347,28.086495,333.943789,336.968300
std,1.963286,42.887477,1.082887,0.734601,2.056275,0.426072,0.836355,0.632823,0.758292,0.953348,1.113135,3.058652,2.364822,1.454177,0.890163,2.303644,1.719971,86.177926,87.105358
min,1.000000,40.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2.000000,1.000000,0.000000,25.000000,69.100000,100.700000
25%,2.000000,80.250000,2.000000,0.000000,3.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,5.900000,3.200000,1.700000,0.000000,26.700000,271.800000,274.250000
50%,4.000000,111.700000,3.000000,0.000000,5.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,0.000000,7.900000,4.400000,2.500000,0.000000,28.200000,332.000000,330.050000
75%,6.000000,140.350000,3.000000,1.000000,7.000000,1.000000,3.000000,1.000000,1.000000,2.000000,3.000000,5.225000,10.100000,5.700000,3.300000,2.000000,29.500000,391.900000,393.275000
max,7.000000,256.700000,6.000000,2.000000,8.000000,2.000000,3.000000,2.000000,2.000000,3.000000,3.000000,9.000000,12.000000,7.000000,4.000000,8.000000,31.000000,558.300000,600.200000

In [20]:
df.isnull().sum()

Month                           0
Province                        0
District                        0
Household_Type                  0
Household_Size                  0
House_Area_m2                  30
Bedrooms                        0
AC_Units                       20
Fans                            0
Refrigerators                   0
TVs                             0
Washing_Machines                0
Water_Heaters                   0
Computers                       0
Other_High_Power_Appliances     0
Avg_Daily_AC_Hours             40
Avg_Daily_Fan_Hours            30
Avg_Daily_TV_Hours              0
Avg_Daily_Cooking_Hours         0
Solar_PV                        0
Solar_Capacity_kW              20
Avg_Temperature_C              30
Previous_Month_kWh             50
Target_Monthly_kWh              0
dtype: int64

In [21]:
df["Target_Monthly_kWh"].describe()

count    1000.000000
mean      336.968300
std        87.105358
min       100.700000
25%       274.250000
50%       330.050000
75%       393.275000
max       600.200000
Name: Target_Monthly_kWh, dtype: float64