In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Shehan\OneDrive\Desktop\PROJECT_\data\cleaned_data.csv")
df.head()

,Month,Province,District,Household_Type,Household_Size,House_Area_m2,Bedrooms,AC_Units,Fans,Refrigerators,...,Other_High_Power_Appliances,Avg_Daily_AC_Hours,Avg_Daily_Fan_Hours,Avg_Daily_TV_Hours,Avg_Daily_Cooking_Hours,Solar_PV,Solar_Capacity_kW,Avg_Temperature_C,Previous_Month_kWh,Target_Monthly_kWh
0,January,Eastern,Ampara,Single_Family,4,69.1,1,1.0,4,1,...,3,5.1,4.7,3.5,3.3,No,0.0,30.3,369.7,350.8
1,January,Eastern,Ampara,Apartment,6,54.1,2,0.0,7,1,...,0,0.0,7.9,6.3,3.0,No,0.0,30.3,290.9,281.8
2,January,North Central,Anuradhapura,Single_Family,2,196.9,5,0.0,3,1,...,1,0.0,10.7,4.1,3.9,No,0.0,25.4,241.6,277.9
3,January,North Central,Anuradhapura,Single_Family,4,122.8,3,0.0,4,2,...,3,0.0,9.2,5.7,3.7,No,0.0,27.4,270.7,286.7
4,January,Uva,Badulla,Single_Family,5,93.9,2,0.0,5,1,...,2,0.0,4.7,2.7,1.4,No,0.0,29.6,307.3,303.0

In [3]:
x=df.drop(columns=["Target_Monthly_kWh"])
y=df["Target_Monthly_kWh"]

In [4]:
x.head()

,Month,Province,District,Household_Type,Household_Size,House_Area_m2,Bedrooms,AC_Units,Fans,Refrigerators,...,Computers,Other_High_Power_Appliances,Avg_Daily_AC_Hours,Avg_Daily_Fan_Hours,Avg_Daily_TV_Hours,Avg_Daily_Cooking_Hours,Solar_PV,Solar_Capacity_kW,Avg_Temperature_C,Previous_Month_kWh
0,January,Eastern,Ampara,Single_Family,4,69.1,1,1.0,4,1,...,3,3,5.1,4.7,3.5,3.3,No,0.0,30.3,369.7
1,January,Eastern,Ampara,Apartment,6,54.1,2,0.0,7,1,...,1,0,0.0,7.9,6.3,3.0,No,0.0,30.3,290.9
2,January,North Central,Anuradhapura,Single_Family,2,196.9,5,0.0,3,1,...,1,1,0.0,10.7,4.1,3.9,No,0.0,25.4,241.6
3,January,North Central,Anuradhapura,Single_Family,4,122.8,3,0.0,4,2,...,3,3,0.0,9.2,5.7,3.7,No,0.0,27.4,270.7
4,January,Uva,Badulla,Single_Family,5,93.9,2,0.0,5,1,...,2,2,0.0,4.7,2.7,1.4,No,0.0,29.6,307.3

In [5]:
y.head()

0    350.8
1    281.8
2    277.9
3    286.7
4    303.0
Name: Target_Monthly_kWh, dtype: float64

In [6]:
x.dtypes

Month                              str
Province                           str
District                           str
Household_Type                     str
Household_Size                   int64
House_Area_m2                  float64
Bedrooms                         int64
AC_Units                       float64
Fans                             int64
Refrigerators                    int64
TVs                              int64
Washing_Machines                 int64
Water_Heaters                    int64
Computers                        int64
Other_High_Power_Appliances      int64
Avg_Daily_AC_Hours             float64
Avg_Daily_Fan_Hours            float64
Avg_Daily_TV_Hours             float64
Avg_Daily_Cooking_Hours        float64
Solar_PV                           str
Solar_Capacity_kW              float64
Avg_Temperature_C              float64
Previous_Month_kWh             float64
dtype: object

In [7]:
categorical_features=x.select_dtypes(include=["object"]).columns
numerical_features=x.select_dtypes(exclude=["object"]).columns

C:\Users\Shehan\AppData\Local\Temp\ipykernel_20344\1170186852.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features=x.select_dtypes(include=["object"]).columns

In [8]:
print("Categorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

Categorical features:
Index(['Month', 'Province', 'District', 'Household_Type', 'Solar_PV'], dtype='str')

Numerical features:
Index(['Household_Size', 'House_Area_m2', 'Bedrooms', 'AC_Units', 'Fans',
       'Refrigerators', 'TVs', 'Washing_Machines', 'Water_Heaters',
       'Computers', 'Other_High_Power_Appliances', 'Avg_Daily_AC_Hours',
       'Avg_Daily_Fan_Hours', 'Avg_Daily_TV_Hours', 'Avg_Daily_Cooking_Hours',
       'Solar_Capacity_kW', 'Avg_Temperature_C', 'Previous_Month_kWh'],
      dtype='str')

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
encoder=OneHotEncoder(handle_unknown="ignore")

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scalar=StandardScaler()

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
preprocessor=ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numerical_features),
        ("cat",OneHotEncoder(handle_unknown="ignore"),categorical_features)
    ]
)

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [16]:
model=Pipeline(
    steps=[
        ("preprocessor",preprocessor),
        ("regressor",LinearRegression())
    ]
)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
print("X_train:", x_train.shape)
print("X_test :", x_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (800, 23)
X_test : (200, 23)
y_train: (800,)
y_test : (200,)